name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env.production from secrets
        run: |
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" >> .env.production
          echo "REACT_APP_WS_BASE_URL=${{ secrets.REACT_APP_WS_BASE_URL }}" >> .env.production

      - name: Install dependencies
        run: npm ci

      - name: Build with environment variables
        run: cross-env REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} REACT_APP_WS_BASE_URL=${{ secrets.REACT_APP_WS_BASE_URL }} CI=false npm run build

      - name: Build with environment variables
        run: npm run build:prod

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHAT_E48D2 }}
          channelId: live
          projectId: chat-e48d2
